# Generated by Django 3.0.8 on 2024-09-18 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240918_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
